[build-system]
requires = ["hatchling>=1.21"]
build-backend = "hatchling.build"

[project]
name = "schevo-mongo"
version = "0.0.0"
description = "MongoDB adapter for Schevo."
requires-python = ">=3.10"
dependencies = ["pymongo", "schevo-core"]

[tool.hatch.build.targets.wheel]
packages = ["schevo_mongo"]
