[build-system]
requires = ["hatchling>=1.21"]
build-backend = "hatchling.build"

[project]
name = "schevo-spark"
version = "0.0.1"
description = "Spark adapter for Schevo."
requires-python = ">=3.10"
dependencies = ["schevo-core", "pyspark"]

[tool.hatch.build.targets.wheel]
packages = ["schevo_spark"]
